### PR TITLE
Talha Khamoor Colonist PingPong Test PR

### PR DESCRIPTION
**Pull request by TalhaKhamoor**
# Talha's Colonist Test - Ping Pong Game PR

Authors: `TalhaKhamoor` `goktugyil`
Implemented a ping pong game according to the template provided.

# Description

The following pull request will take the given template and add to it all the functionalities 
needed to run a ping pong game between two players. 

https://user-images.githubusercontent.com/59896329/135393638-d7688de6-d369-4457-bdb4-f9647f0ea33c.mp4

These are the following functionalities added to the game: 

    - Made the game cover the whole browser
    - Added keyboard functionalities for both players, W and S for one player, Up and Down for another player.
    - Added players into canvas, making sure we can move players with the keyboard.
    - Added ball to the game, pressing `SPACE` button start's and pauses the game, made sure the ball bounces from boundaries.
    - When a player scores, scoring is shown with console.log as well as on canvas. The game is then reset.
    - Added draw text functionality to the engine. Introductory instructions and game title.
    - Added score system for the game and used the drawText functionality on the game.
    - Added resize functionality
    - Made the ball round

Most of these changes were done by editing the index.html file. More specifically, I added a lot more functionality to the script that was in there. Some changes were made to the HTML side of things. Nothing too major in that regard. The app.js file had some functionalities added to it in order to make the drawing of the circle possible as well as the text. 

The changes made in the index.html file were mostly done on the onInit and onUpdate functions. A lot of helper functions were refactored and extracted from the init function in order to make it look neater and function better. Lastly, the index.html file also had the addition of the reset and pause functions in order to allow for those functionalities. 

To run the app, download the application off of the repo. Make sure you have node.js installed. Go into your terminal and navigate to the folder that contains the index.js file. Use npm init to set up/create npm package. Use npm to install express. run node index.js to start the application.

### CODE REVIEW

**Comment by TalhaKhamoor** [comment]
Hope you folks don't mind me merging my feature branch into my main one here. Was thinking that 

"On your repository create a PR merging your feature branch into your master branch."

meant for me to close this pull request.

**Comment by demiculus** [comment]
Hey @TalhaKhamoor 

Nice work, can you do some edits?
Branch off of this branch and continue on the new branch. Then create a new PR merging that new branch to this one and tag me for review.

At the new branch, I want to see a couple of things

1. Clean commits: Commits are too big, confusing etc. Google best commit practices and apply them in your workflow. 
2. Clean code: Your code works but it is not clean. Google clean code best practices & principles and apply some of them. In your PR description include which ones you applied and any detail you feel would add value. (please remove all the comments, they are killing me 🙏 )
3. Fun mechanic: The game is a bit boring. Add any mechanic that you think would make the game more fun.

Let me know if there are any questions.

**Comment by TalhaKhamoor** [comment]
Thanks for the review @demiculus

I definitely went a little overboard with the commenting 😂. I will get rid of them for my next pull request. I also did a little bit of reading on clean commit and coding practices last night, and so ill make sure to implement those as well - along with making the game more fun.

**Comment by demiculus** [comment]
Cool please put this commet in the description on the new PR https://github.com/TalhaKhamoor/PingPongGame/pull/1#issuecomment-932895088

**Pull request merged**
